<?php declare(strict_types=1);?>
<script type="text/x-magento-init">
    {
        "#registartion":{
            "Magento_Ui/js/core/app":{
                "components":{
                    "registartion":{
                        "component": "Am_Module/js/registartion-test",
                        "config": {
                            "registartionUrl":"<?= $block->getStoreId()?>"
                        }
                    }
                }
            }
        }
    }
</script>
<div id="registartion"></div>
<h1>dfdjhdfdjhf</h1>
